# Generated by Django 5.2.4 on 2025-07-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_padel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paleta',
            name='author',
        ),
    ]
