# Generated by Django 5.2.3 on 2025-07-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('tipo', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
